default: 
	echo "Target not specified"
	exit 1

ansible-update-home-ubuntu-desktops:
	ansible-playbook node-home-desktops.yml -K
	
ansible-update-home-ubuntu-servers:
	ansible-playbook node-home-servers.yml -K

ansible-update-home-media-servers:
	ansible-playbook node-media-servers.yml -K
